# Generated by Django 5.2.11 on 2026-03-15 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('vendedor', 'Vendedor'), ('comprador', 'Comprador'), ('corretor', 'Corretor'), ('backoffice', 'Backoffice')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('venda', 'Oferta de Venda'), ('compra', 'Ordem de Compra')], max_length=10)),
                ('grain', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit', models.CharField(default='Sacas', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=120)),
                ('crop', models.CharField(max_length=10)),
                ('shipping', models.CharField(choices=[('FOB', 'FOB'), ('CIF', 'CIF')], max_length=3)),
                ('quality', models.JSONField(default=dict)),
                ('payment_terms', models.CharField(max_length=120)),
                ('status', models.CharField(default='ativa', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.user')),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proposed_quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('brokerage_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buy_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_buys', to='market.offer')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='market.offer')),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brokered', to='market.user')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='market.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='market.user')),
            ],
        ),
    ]
