# Generated by Django 5.2.11 on 2026-03-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='brokerage_mode',
            field=models.CharField(choices=[('percentage', 'Percentual'), ('per_sack', 'Valor por saca')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='brokerage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='brokerage_value_per_sack',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
