# Generated by Django 5.2.11 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_negotiation_brokerage_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='brokerage_mode',
            field=models.CharField(
                choices=[
                    ('percentage', 'Percentual'),
                    ('fixed', 'Valor fixo'),
                    ('per_sack', 'Valor por saca'),
                ],
                default='percentage',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='negotiation',
            name='brokerage_payer',
            field=models.CharField(
                choices=[('seller', 'Vendedor'), ('buyer', 'Comprador')],
                default='seller',
                max_length=10,
            ),
        ),
    ]
