# Generated by Django 5.2.11 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_negotiation_brokerage_payer_and_fixed_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiation',
            name='brokerage_mode',
            field=models.CharField(
                choices=[
                    ('percentage', 'Percentual'),
                    ('fixed', 'Valor fixo'),
                    ('per_sack', 'Valor por saca'),
                    ('spread', 'Spread'),
                ],
                default='percentage',
                max_length=20,
            ),
        ),
    ]
