# Generated by Django 5.2.11 on 2026-04-17 20:04

import uuid
import django.db.models.deletion
from django.db import migrations, models


def populate_broker_link_tokens(apps, schema_editor):
    User = apps.get_model('market', 'User')
    for user in User.objects.filter(broker_link_token__isnull=True):
        user.broker_link_token = uuid.uuid4()
        user.save(update_fields=['broker_link_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_negotiation_spread_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='direct_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='direct_payment_status',
            field=models.CharField(choices=[('free', 'Isenta'), ('pending', 'Aguardando pagamento'), ('paid', 'Pago')], default='free', max_length=12),
        ),
        migrations.AddField(
            model_name='offer',
            name='exclusive_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exclusive_marketplace_offers', to='market.user'),
        ),
        migrations.AddField(
            model_name='offer',
            name='mesa_commission',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='negotiation_channel',
            field=models.CharField(choices=[('mesa', 'Operando com a mesa'), ('direta', 'Oferta direta')], default='mesa', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='broker_link_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.RunPython(populate_broker_link_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('aguardando_pagamento', 'Aguardando pagamento')], default='ativa', max_length=24),
        ),
    ]
