# Generated by Django 5.2.11 on 2026-04-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_user_address_city_user_address_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=True),
        ),
    ]
