# Generated by Django 5.2.11 on 2026-04-25 14:19

from django.db import migrations, models


def normalize_document(value):
    return ''.join(char for char in str(value or '') if char.isdigit())[:14]


def backfill_document_digits(apps, schema_editor):
    User = apps.get_model('market', 'User')
    seen = {}

    for user in User.objects.exclude(document_number='').only('id', 'document_number'):
        digits = normalize_document(user.document_number)
        if not digits:
            continue
        if digits in seen:
            user.document_number_digits = ''
            user.save(update_fields=['document_number_digits'])
            continue
        seen[digits] = user.id
        user.document_number_digits = digits
        user.save(update_fields=['document_number_digits'])


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_user_legal_acceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_number_digits',
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
        migrations.RunPython(backfill_document_digits, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('document_number_digits', ''), _negated=True), fields=('document_number_digits',), name='unique_user_document_number_digits'),
        ),
    ]
