# Generated by Django 5.2.11 on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_user_document_number_digits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('buyer', 'Comprador'), ('seller', 'Vendedor')], max_length=10)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'negotiation',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='market.negotiation'),
                ),
                (
                    'sender',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='negotiation_messages',
                        to='market.user',
                    ),
                ),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='negotiationmessage',
            index=models.Index(fields=['negotiation', 'audience', 'created_at'], name='market_nego_negotia_3dcebb_idx'),
        ),
    ]
