# Generated by Django 5.2.11 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_negotiationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationmessage',
            name='delivery_channel',
            field=models.CharField(choices=[('app', 'Aplicacao'), ('whatsapp', 'WhatsApp')], default='app', max_length=20),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='delivery_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='negotiationmessage',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
